version: '3'
services:

  rabbitmq:
    image: rabbitmq
    ports: 
      - '5672:5672'

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./client/.env.local
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  auth:
    restart: always
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    command: npm start
    env_file:
     - ./backend/auth/.env
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - ./backend/auth:/usr/src/app
      - /usr/src/app/node_modules
    hostname: auth
    ports:
      - "4000:4000"

  workouts:
    restart: always
    build:
      context: ./backend/workouts
      dockerfile: Dockerfile
    command: npm start
    env_file:
     - ./backend/workouts/.env
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - ./backend/workouts:/usr/src/app
      - /usr/src/app/node_modules
    hostname: workouts
    ports:
      - "4001:4001"


  exercises:
    restart: always
    build:
      context: ./backend/exercises
      dockerfile: Dockerfile
    command: npm start
    env_file:
     - ./backend/exercises/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend/exercises:/usr/src/app
      - /usr/src/app/node_modules
    hostname: exercises
    ports:
      - "4002:4002"
volumes:
  dbdata6:
