import type { Metadata } from 'next'
import './signup.module.css';
import styles from './signup.module.css';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className={styles.main}>
          {children}
      </div>
  )
}
