import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './signup.module.css';
import styles from './signup.module.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className={styles.main}>
          {children}
      </div>
  )
}
