import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SessionProvider from './components/SessionProvider';
import { getServerSession } from 'next-auth';
import styles from './page.module.css'
import StyledComponentsRegistry from './lib/registry'
import { MainContainer } from './components/styled/MainContainer.styled';
import { Container } from './components/styled/Container.styled';
import NavigationMenu from './components/NavigationMenu';
import Theme from './lib/Theme';
import BreadCrumbs from './components/BreadCrumbs';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session =  await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.main}`}>
        <Theme>
        
          <MainContainer className={inter.className}>
            
            <StyledComponentsRegistry>
              <SessionProvider session={session}> 
                <NavigationMenu/>
                <div style={{flex:1}}>
                
                <Container>
                <BreadCrumbs />
                  {children}
                </Container>
                </div>
              
              </SessionProvider> 
            </StyledComponentsRegistry>
          </MainContainer>
        </Theme>
        </body>
    </html>
  )
}
